Update test_service.py
nyu-devops-fall19-suppliers/suppliers pull request #175
Opened 2019-12-09 15:48 UTC by lhmartin

Add extra test the will run before the behave tests and therefore fix the walmart bug.

2019-12-09 16:24 UTC, silemie requested changes
Hi Luke, I think you should add an API-key header in the delete request to pass delete the authorization check

2019-12-09 17:57 UTC, lhmartin commented
> Hi Luke, I think you should add an API-key header in the delete request to pass delete the authorization check

Thanks will do

2019-12-09 20:26 UTC, Krystal-158 approved these changes

2019-12-10 00:37 UTC, silemie approved these changes

2019-12-10 00:56 UTC, greenson approved these changes

2019-12-10 00:57 UTC, merged